package com.puttysoftware.lasertank.strings;

public enum DialogString {
    DEAD_MESSAGE, DEAD_TITLE, UNDO_BUTTON, RESTART_BUTTON, END_BUTTON, RESOURCES_MESSAGE, CANCEL_BUTTON, SCORES_HEADER,
    SCORE_ENTRY, LOADING, ARENA_LOADING_SUCCESS, ARENA_LOADING_FAILED, ARENA_LEVEL, ARENA_LEVEL_BY,
    GAME_LOADING_SUCCESS, GAME_LOADING_FAILED, NON_ARENA_FILE, ILLEGAL_CHARACTERS, PROMPT_SAVE_ARENA, PROMPT_SAVE_GAME,
    ARENA_SAVING_FAILED, GAME_SAVING_FAILED, LOAD, SAVE, ABOUT, VERSION, AUTHOR, WEB_SITE, BUG_REPORTS, OK_BUTTON,
    EXPORT_BUTTON, HELP, NON_PLAYBACK_FILE, CHEATS, IMPORT_FAILED_FILE_TYPE, IMPORT_FAILED_NON_FILE, IMPORT_TITLE,
    IMPORT_INSTRUCTIONS, PROTECTION_PROMPT, PROTECTION_TITLE, UPDATING_LEVEL_INFO;
}
