package com.puttysoftware.lasertank.strings;

public enum EditorString {
    EDITOR_TITLE_1, EDITOR_TITLE_2, NO_PROPERTIES, SET_START_POINT, START_POINT_SET, AIM_WITHIN_THE_ARENA,
    ARENA_CREATED, ARENA_CREATION_FAILED, CONFIRM_CANNOT_BE_UNDONE, EDITOR, LEVEL_FILLED, LEVEL_ADDED,
    LEVEL_ADDING_FAILED, WHICH_LEVEL_TO_REMOVE, REMOVE_LEVEL, RESIZE_LEVEL, NUMBER_OF_FLOORS, FLOORS_TOO_LOW,
    FLOORS_TOO_HIGH, GO_TO_LEVEL, GO_TO_WHICH_LEVEL, NOTHING_TO_UNDO, NOTHING_TO_REDO, LEVEL_PREFERENCES,
    ENABLE_HORIZONTAL_WRAP_AROUND, ENABLE_VERTICAL_WRAP_AROUND, ENABLE_THIRD_DIMENSION_WRAP_AROUND, LEVEL_NAME,
    LEVEL_AUTHOR, LEVEL_HINT, LEVEL_DIFFICULTY, MUSIC_EDITOR, MUSIC_PLAY, MUSIC_STOP, MUSIC_MODIFY, HORZ_JUMP,
    VERT_JUMP, LOWER_GROUND_LAYER, UPPER_GROUND_LAYER, LOWER_OBJECTS_LAYER, UPPER_OBJECTS_LAYER, CHANGE_LAYER_PROMPT,
    ENABLE_MOVE_SHOOT;
}
