package com.puttysoftware.lasertank.strings;

public enum ErrorString {
    ERROR_TITLE, ERROR_MESSAGE, TANK_LOCATION, TEMP_DIR, INVALID_CHEAT, LPB_LOAD_FAILURE, NO_PREVIOUS_LEVEL,
    NO_SOLUTION_FILE, LTG_LOAD_FAILURE, PRINTING_FAILURE, UNKNOWN_ARENA_FORMAT, UNKNOWN_OBJECT, BAD_PROTECTION_KEY,
    PROTECTION, NONFATAL_TITLE, NONFATAL_MESSAGE;
}
