package com.puttysoftware.lasertank.strings;

public enum GameString {
    LOAD_PLAYBACK, PLAYBACK_LOADED, PLAYBACK_LOAD_FAILED, CHEAT_PROMPT, CHEAT_ACTION, ENABLE_CHEAT, DISABLE_CHEAT,
    MISSILES, STUNNERS, BLUE_LASERS, BOOSTS, MAGNETS, MOVES, SHOTS, OTHERS, LEVEL, INFINITE, OUT_OF_MISSILES,
    OUT_OF_STUNNERS, OUT_OF_BLUE_LASERS, OUTSIDE_ARENA, WHICH_AMMO, CHANGE_AMMO, AMMO_CHANGED, WHICH_TOOL, CHANGE_TOOL,
    TOOL_CHANGED, LOAD_LEVEL_PROMPT, LOAD_LEVEL, IDENTIFY_OBJECT, NO_LEVEL_WITH_DIFFICULTY, SELECT_DIFFICULTY,
    OUT_OF_BOOSTS, OUT_OF_MAGNETS, SCORE_MOVES, SCORE_SHOTS, SCORE_OTHERS, SCORES_UNAVAILABLE, SCORES, DISRUPTORS,
    OUT_OF_DISRUPTORS, BOMBS, OUT_OF_BOMBS, WHICH_RANGE, CHANGE_RANGE, RANGE_CHANGED, HEAT_BOMBS, OUT_OF_HEAT_BOMBS,
    ICE_BOMBS, OUT_OF_ICE_BOMBS, TIME_TRAVEL_ENABLED;
}
