package com.puttysoftware.lasertank.strings;

public enum GenericString {
    COLOR_BLUE, COLOR_CYAN, COLOR_GRAY, COLOR_GREEN, COLOR_MAGENTA, COLOR_RED, COLOR_WHITE, COLOR_YELLOW, NORTHWEST,
    NORTH, NORTHEAST, EAST, SOUTHEAST, SOUTH, SOUTHWEST, WEST, HORIZONTAL, VERTICAL, TUNNEL, UN_NAMED_LEVEL,
    UNKNOWN_AUTHOR;
}
