package com.puttysoftware.lasertank.strings;

public enum MenuString {
    MENU_FILE, MENU_EDIT, MENU_PLAY, MENU_GAME, MENU_EDITOR, MENU_OVERRIDE, MENU_HELP, ITEM_NEW, ITEM_OPEN, ITEM_CLOSE,
    ITEM_SAVE, ITEM_SAVE_AS, ITEM_PRINT_GAMEBOARD, ITEM_EXIT, ITEM_QUIT, ITEM_UNDO, ITEM_REDO, ITEM_CUT_LEVEL,
    ITEM_COPY_LEVEL, ITEM_PASTE_LEVEL, ITEM_INSERT_LEVEL_FROM_CLIPBOARD, ITEM_PREFERENCES, ITEM_CLEAR_HISTORY,
    ITEM_PLAY, ITEM_EDIT, ITEM_USE_CLASSIC_ACCELERATORS, ITEM_RESET_CURRENT_LEVEL, ITEM_SHOW_SCORE_TABLE,
    ITEM_REPLAY_SOLUTION, ITEM_RECORD_SOLUTION, ITEM_LOAD_PLAYBACK_FILE, ITEM_PREVIOUS_LEVEL, ITEM_SKIP_LEVEL,
    ITEM_LOAD_LEVEL, ITEM_SHOW_HINT, ITEM_CHEATS, ITEM_CHANGE_OTHER_AMMO, ITEM_CHANGE_OTHER_TOOL, ITEM_GO_TO_LEVEL,
    ITEM_UP_ONE_FLOOR, ITEM_DOWN_ONE_FLOOR, ITEM_UP_ONE_LEVEL, ITEM_DOWN_ONE_LEVEL, ITEM_ADD_A_LEVEL,
    ITEM_REMOVE_A_LEVEL, ITEM_FILL_CURRENT_LEVEL, ITEM_RESIZE_CURRENT_LEVEL, ITEM_LEVEL_PREFERENCES,
    ITEM_SET_START_POINT, ITEM_CHANGE_LAYER, ITEM_REVERT_RESOURCES, ITEM_LOAD_GRAPHICS_FILE, ITEM_GRAPHICS_FILE_INFO,
    ITEM_CHECK_FOR_UPDATES, ITEM_CHECK_FOR_BETA_UPDATES, ITEM_ABOUT_LASERTANK, ITEM_LASERTANK_HELP,
    ERROR_NO_ARENA_OPENED, CONFIRM_CLEAR_HISTORY, CONFIRM_RESET_CURRENT_LEVEL, ITEM_CHANGE_OTHER_RANGE, ITEM_SET_MUSIC,
    ITEM_SAVE_AS_PROTECTED, ITEM_OPEN_DEFAULT, ITEM_ENABLE_GLOBAL_MOVE_SHOOT, ITEM_DISABLE_GLOBAL_MOVE_SHOOT,
    SUB_TIME_TRAVEL;
}
