package com.puttysoftware.lasertank.strings;

public enum PrefString {
    TITLE, ENABLE_SOUNDS, STARTUP_UPDATES, STARTUP_BETA_UPDATES, ONE_MOVE, ENABLE_ANIMATION, SPEED_1, SPEED_2, SPEED_3,
    SPEED_4, SPEED_5, SPEED_LABEL, ACTIVE_LANGUAGE_LABEL, ENABLE_MUSIC, EDITOR_LAYOUT_LABEL, EDITOR_LAYOUT_CLASSIC,
    EDITOR_LAYOUT_MODERN_V11, EDITOR_LAYOUT_MODERN_V12, SHOW_ALL_OBJECTS;
}
