package com.puttysoftware.lasertank.dataload;

enum DataFile {
    SOLID, SOLID_ATTRIBUTE, DIRECTION, FRAME, FRICTION, INDEX, MOVABLE, SHOOT, WEIGHT, TRANSFORM_FIRE, TRANSFORM_ICE,
    TRANSFORM_STONE, MATERIAL, HEIGHT, LAYER, LETHAL, REFLECT_EAST, REFLECT_NORTH, REFLECT_SOUTH, REFLECT_WEST;
}
